# "prettier options": "https://prettier.io/docs/en/options.html"

singleQuote: true
trailingComma: all
proseWrap: never
endOfLine: lf
quoteProps: consistent
jsxSingleQuote: true
semi: false
useTabs: false
xmlWhitespaceSensitivity: 'ignore'
plugins:
  - '@prettier/plugin-xml'
overrides:
  - files: '*.svg'
    options: { parser: 'xml' }
